export const translate = {
  sr: {
    Početna: "Početna",

    "Gallos obećava nezaboravne trenutke stvorene uz najukusnije pileće obroke sa roštilja na svetu.":
      "Gallos obećava nezaboravne trenutke stvorene uz najukusnije pileće obroke sa roštilja na svetu.",
    "Pileće meso je marinirano u najsvežijim sastojcima najmanje 48 sati, u raznim ukusima kao što su Limun i Bilje, Blago ljuto, Ljuto i Beli luk":
      "Pileće meso je marinirano u najsvežijim sastojcima najmanje 48 sati, u raznim ukusima kao što su Limun i Bilje, Blago ljuto, Ljuto i Beli luk",
    "STICKY DATE PUDDING": "STICKY DATE PUDDING",
    "Hrskavi krompirići sa topljenim čedar sirom": "Hrskavi krompirići sa topljenim čedar sirom",
    "Trakice pilećeg filea & servirano sa pomfritom": "Trakice pilećeg filea & servirano sa pomfritom",
    "Ajsberg salata, paprika, krastavac, paradajz, italijanski dresing": "Ajsberg salata, paprika, krastavac, paradajz, italijanski dresing",
    "Vidite naš meni": "Vidite naš meni",
    "Flame grilled chicken": "CLASSIC GRILLED",
    "Supe i salate": "Supe i salate",
    "Komadići pilećeg filea & servirano sa pomfritom": "Komadići pilećeg filea & servirano sa pomfritom",
    "SLADOLED": "SLADOLED",
    "Grilovane šargarepe, paprika, beli luk, pečurke, tikvice, crni luk, origano": "Grilovane šargarepe, paprika, beli luk, pečurke, tikvice, crni luk, origano",
    "Hrskavi krompirići": "Hrskavi krompirići",
    "Činije pirinča": "RICE BOWLS",
    "Šargarepa, kupus, majonez": "Šargarepa, kupus, majonez",
    Promocija: "Promocija",
    "PILEĆA DŽIGERICA BOWL": "PILEĆA DŽIGERICA BOWL",
    Prilozi: "Prilozi",
    "Hrskavi batat krompirići": "Hrskavi batat krompirići",
    Jela: "Jela",
    "Naš meni": "Naš meni",
    "GRILL MASTER’S SALATA": "GRILL MASTER’S SALATA",
    "PILEĆI TENDERSI": "PILEĆI TENDERSI",
    "Mekani kolač od urmi, sladoled od vanile, karamel sos": "Mekani kolač od urmi, sladoled od vanile, karamel sos",
    "Razgovarajte sa nama": "Razgovarajte sa nama",
    Meni: "Meni",
    "Naša istorija": "Naša istorija",
    "CHEESY POMFRIT": "CHEESY POMFRIT",
    "DEČIJI MENI": "DEČIJI MENI",
    "Ciabatta hleb, puter od belog luka": "Ciabatta hleb, puter od belog luka",
    Kontakt: "Kontakt",
    Sosevi: "Sosevi",
    "Naša priča": "Naša priča",
    "BASMATI PIRINAČ": "Basmati pirinač",
    "Pileća krilca grilovana na plamenu": "Pileća krilca grilovana na plamenu",
    "PILEĆI NUGGETS": "PILEĆI NUGGETS",
    "Naša priča": "Naša priča",
    DEZERTI: "DEZERTI",
    "HOMEMADE NUTELLA BROWNIE": "HOMEMADE NUTELLA BROWNIE",
    "Kugla sladoleda od vanile": "Kugla sladoleda od vanile",
    "PILEĆA ESPETADA": "PILEĆA ESPETADA",
    "Gallos halal piri piri piletina pečena na plamenu predstavlja pravo uživanje na tanjiru. Nudi savršen nivo ljutine u kombinaciji sa bogatim, neodoljivim slojevima ukusa. Naša kućna marinada napravljena je od 100% prirodnih sastojaka i pažljivo odabranih začina i biljaka, omogućavajući piletini da upije bogat ukus tokom najmanje 24 sata. Sveže pečena na vatri po porudžbini, sa prepoznatljivom sočnom koricom — to je najukusnija i najkvalitetnija portugalska piletina pečena na plamenu u okolini. Želite Gallos ukus i kod kuće? Nabavite naše ekskluzivne sosove, marinade ili već marinirane pileće filete (flatties) u varijantama: limun i začinsko bilje, blago i ljuto.":
      "Gallos halal piri piri piletina pečena na plamenu predstavlja pravo uživanje na tanjiru. Nudi savršen nivo ljutine u kombinaciji sa bogatim, neodoljivim slojevima ukusa. Naša kućna marinada napravljena je od 100% prirodnih sastojaka i pažljivo odabranih začina i biljaka, omogućavajući piletini da upije bogat ukus tokom najmanje 24 sata. Sveže pečena na vatri po porudžbini, sa prepoznatljivom sočnom koricom — to je najukusnija i najkvalitetnija portugalska piletina pečena na plamenu u okolini. Želite Gallos ukus i kod kuće? Nabavite naše ekskluzivne sosove, marinade ili već marinirane pileće filete (flatties) u varijantama: limun i začinsko bilje, blago i ljuto.",
    "27 godina iskustva": "27 godina iskustva",
    "Naša hrana je srce svega što radimo.":
      "Naša hrana je srce svega što radimo.",
    "Grilovana pileća krilca na otvorenom plamenu, servirano sa pomfritom, izbor sosa/Choice of spice level":
      "Grilovana pileća krilca na otvorenom plamenu, servirano sa pomfritom, izbor sosa/Choice of spice level",
    "Serviramo 100% pileće meso sa roštilja, marinirano samo najboljim sastojcima, u raznim ukusima - BBQ, Limun i Bilje, Blago ljuto, Ljuto i Extra Ljuto Piri-Piri.":
      "Serviramo 100% pileće meso sa roštilja, marinirano samo najboljim sastojcima, u raznim ukusima - BBQ, Limun i Bilje, Blago ljuto, Ljuto i Extra Ljuto Piri-Piri.",
    "Nalazimo se u centru grada.": "Nalazimo se u centru grada.",
    "Sveže sastojke dobavljamo sa organskih farmi.":
      "Sveže sastojke dobavljamo sa organskih farmi.",
    "Brza dostava u vlasništvu. Maksimalno 30 minuta.":
      "Brza dostava u vlasništvu. Maksimalno 30 minuta.",
    "Profesionalni, iskusni kuvari.": "Profesionalni, iskusni kuvari.",
    "Najviši standardi usluge.": "Najviši standardi usluge.",
    "100% zadovoljstvo": "100% zadovoljstvo",
    "ZAŠTO IZABRATI GALLO'S?": "ZAŠTO IZABRATI GALLO'S?",
    "Zato što verujemo da dobra hrana mora imati dušu. Svako jelo pripremamo s pažnjom, biramo samo proverene sastojke i trudimo se da svaki zalogaj donese isti osećaj zadovoljstva. Kod nas vas uvek čeka toplo gostoprimstvo, autentičan ukus i iskustvo kojem ćete se rado vraćati.":
      "Zato što verujemo da dobra hrana mora imati dušu. Svako jelo pripremamo s pažnjom, biramo samo proverene sastojke i trudimo se da svaki zalogaj donese isti osećaj zadovoljstva. Kod nas vas uvek čeka toplo gostoprimstvo, autentičan ukus i iskustvo kojem ćete se rado vraćati.",
    "Izvanredna usluga": "Izvanredna usluga",
    "Hrskavi krompirići sa piri-piri začinima": "Hrskavi krompirići sa piri-piri začinima",
    "Hrana je bila izvanredna, a usluga je bila brza i vrlo profesionalna. Kvalitet obroka je bio sjajan, i zaista sam uživala u svakom zalogaju. Izvanredna usluga.":
      "Hrana je bila izvanredna, a usluga je bila brza i vrlo profesionalna. Kvalitet obroka je bio sjajan, i zaista sam uživala u svakom zalogaju.Izvanredna usluga.",
    "Iskustvo u ovom restoranu bilo je fantastično! Hrana je bila sveža i ukusna, a osoblje je bilo veoma ljubazno. Definitivno ću se vratiti. Izvanredna usluga":
      "Iskustvo u ovom restoranu bilo je fantastično! Hrana je bila sveža i ukusna, a osoblje je bilo veoma ljubazno. Definitivno ću se vratiti. Izvanredna usluga",
    "Ovaj restoran stvarno zna kako da zadovolji svoje goste. Hrana je bila sočna i puna ukusa, a usluga je bila izuzetno profesionalna. Preporučila bih ga svima!":
      "Ovaj restoran stvarno zna kako da zadovolji svoje goste. Hrana je bila sočna i puna ukusa, a usluga je bila izuzetno profesionalna. Preporučila bih ga svima!",
    "Nisam mogao biti srećniji što sam odlučio jesti u ovom restoranu. Kvalitet hrane je bio vrhunski, a brza dostava je dodala dodatni plus. Ovo mesto je zaista vredno posete.":
      "Nisam mogao biti srećniji što sam odlučio jesti u ovom restoranu. Kvalitet hrane je bio vrhunski, a brza dostava je dodala dodatni plus. Ovo mesto je zaista vredno posete.",
    "Piri-Piri savršenstvo": "Piri-Piri savršenstvo",
    "NA DOHVAT RUKE": "NA DOHVAT RUKE",
    "Preuzmite Galllo's aplikaciju.": "Preuzmite Galllo's aplikaciju.",
    "UKUS KAO KOD KUĆE.": "UKUS KAO KOD KUĆE.",
    "Imamo različite Galllo's jedinstvene soseve kako biste mogli da ih isprobate kod nas.":
      "Imamo različite Galllo's jedinstvene soseve kako biste mogli da ih isprobate kod nas.",
    "STUPITE U KONTAKT SA NAMA": "STUPITE U KONTAKT SA NAMA",
    "Ako želite da nam ispričate svoje iskustvo u Gallos'su ili želite saznati više o nama, nalazite se na pravom mestu. Pišite nam na mejl i mi ćemo vam odgovoriti.":
      "Ako želite da nam ispričate svoje iskustvo u Gallos'su ili želite saznati više o nama, nalazite se na pravom mestu. Pišite nam na mejl i mi ćemo vam odgovoriti.",
    "O nama": "O nama",
    "Pošalji poruku": "Pošalji poruku",
    "Naš email:": "Naš email:",
    "FLAME GRILLED CHICKEN":"CLASSIC GRILLED",
    "CLASSIC GRILLED":"CLASSIC GRILLED",
    "CLASSIC GRILLED": "CLASSIC GRILLED",
    "BURGERI I WRAPOVI": "BURGERI I WRAPOVI",
    "GALLOS PILEĆI BURGER": "GALLOS PILEĆI BURGER",
    "Grilovani pileći file, majonez, čedar sir, paradajz & servirano sa pomfritom": "Grilovani pileći file, majonez, čedar sir, paradajz & servirano sa pomfritom",
    "SMASH BEEF BURGER": "SMASH BEEF BURGER",
    "Mlevena junetina, čedar sir, karamelizovani luk, kiseli krastavci, domaći burger sos & servirano sa pomfritom": "Mlevena junetina, čedar sir, karamelizovani luk, kiseli krastavci, domaći burger sos & servirano sa pomfritom",
    "PIRI PILEĆI BURGER": "PIRI PILEĆI BURGER",
    "Grilovane trake od pilećeg filea, majonez, ajsberg salata, paradajz, čedar sir & servirano sa pomfritom.": "Grilovane trake od pilećeg filea, majonez, ajsberg salata, paradajz, čedar sir & servirano sa pomfritom.",
    "Kontakt telefon:": "Kontakt telefon:",
    "BATAK OBROK": "BATAK OBROK",
    "Grilovani pileći batak sa coleslaw  salatom": "Grilovani pileći batak sa coleslaw  salatom",
    "HRSKAVI BURGER": "HRSKAVI BURGER",
    "Hrskavi pileći file uvaljan u panko čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom. <b>Regular / Nashville ljuti</b>": "Hrskavi pileći file uvaljan u panko čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom. <b>Regular / Nashville ljuti</b>",
    "PODELI OBROK": "PODELI OBROK",
    "CELO PILE": "CELO PILE",
    "PILEĆI BOX 3": "PILEĆI BOX 3",
    "Tri komada piletine grilovane piletine na otvorenom plamenu, servirano sa pomfritom": "Tri komada piletine grilovane piletine na otvorenom plamenu, servirano sa pomfritom",
    "PILEĆI BOX 5": "PILEĆI BOX 5",
    "Pet komada piletine grilovane na otvorenom plamenu, servirano sa pomfritom": "Pet komada piletine grilovane na otvorenom plamenu, servirano sa pomfritom",
    "Grilovana piletina na otvorenom plamenu, servirana uz pirinač, tortilju sa belim lukom i svežom salsom.": "Grilovana piletina na otvorenom plamenu, servirana uz pirinač, tortilju sa belim lukom i svežom salsom.",
    "GRILOVANI PILEĆI FILE SA POMFRITOM": "GRILOVANI PILEĆI FILE SA POMFRITOM",
    "Grilovani pileći file": "Grilovani pileći file",
    "CAESAR WRAP": "CAESAR WRAP",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dresing & servirano sa pomfritom": "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dresing & servirano sa pomfritom",
    "Četiri parčeta piletine grilovane na otvorenom plamenu, dve porcije pomfrita, ciabatta hleb, dva pića (po izboru)": "Četiri parčeta piletine grilovane na otvorenom plamenu, dve porcije pomfrita, ciabatta hleb, dva pića (po izboru)",
    "Celo pile grilovano na otvorenom plamenu u prethodno odležaloj našoj specijalnoj marinadi. Servirano sa: dva priloga po vašem izboru.": "Celo pile grilovano na otvorenom plamenu u prethodno odležaloj našoj specijalnoj marinadi. Servirano sa: dva priloga po vašem izboru.",
    "Osam parčeta piletine grilovane na otvorenom plamenu, četiri porcije pomfrita, ciabatta hleb, četiri pića (po tvom izboru)": "Osam parčeta piletine grilovane na otvorenom plamenu, četiri porcije pomfrita, ciabatta hleb, četiri pića (po tvom izboru)",
    "CEPKANA PILETINA WRAP": "CEPKANA PILETINA WRAP",
    "Cepkana piletina grilovana na otvorenom plamenu, crni luk, paprika, ajsberg salata, majonez, čedar, sishebo sos & servirano sa pomfritom": "Cepkana piletina grilovana na otvorenom plamenu, crni luk, paprika, ajsberg salata, majonez, čedar, sishebo sos & servirano sa pomfritom",
    "PILEĆI FILE": "PILEĆI FILE",
    "GRILOVANI PILEĆI WRAP": "GRILOVANI PILEĆI WRAP",
    "Mlevena piletina, homemade burger sos, sir, ajsberg": "Mlevena piletina, homemade burger sos, sir, ajsberg",
    "Naša adresa": "Naša adresa",
    "Nivo 2, Galerija Mall (parking A), Bulevar Vudroa Vilsona 12, 11000 Beograd":
      "Nivo 2, Galerija Mall (parking A), Bulevar Vudroa Vilsona 12, 11000 Beograd",
    "Čika Ljubina 7":
      "Čika Ljubina 7",
    godina: "godina",
    iskustva: "iskustva",
    "GRILOVANA PILEĆA KRILCA 500G": "GRILOVANA PILEĆA KRILCA 500G",
    "Pileća krilca grilovana na otvorenom plamenu": "Pileća krilca grilovana na otvorenom plamenu",
    PREDJELA: "PREDJELA",
    "PILEĆA DŽIGERICA": "PILEĆA DŽIGERICA",
    "Grilovana pileća džigerica, sishebo sos, hleb sa belim lukom":
      "Grilovana pileća džigerica, sishebo sos, hleb sa belim lukom",
    "PIRI PEČURKE (V)": "PIRI PEČURKE (V)",
    "Grilovani šampinjoni u šišebo sosu i hlebom sa belim lukom i začinima":
      "Grilovani šampinjoni u šišebo sosu i hlebom sa belim lukom i začinima",
    "PILEĆI SATAY": "PILEĆI SATAY",
    "Grilovani pileći file na štapiću sa piri-piri sosem od kikirikija":
      "Grilovani pileći file na štapiću sa piri-piri sosem od kikirikija",
      "PILEĆI POPCORN": "PILEĆI POPCORN",
    "Kokice/kockice od pohovanog pilećeg filea, pomfrit, topljeni sos od čedar sira":
      "Kokice/kockice od pohovanog pilećeg filea, pomfrit, topljeni sos od čedar sira",
    "Hleb sa belim lukom sa kockicama grilovane piletine, majonezom i mocarela sirom":
      "Hleb sa belim lukom sa kockicama grilovane piletine, majonezom i mocarela sirom",
    "CEPKANI PILEĆI TAKOSI":
      "CEPKANI PILEĆI TAKOSI",
    "Cepkana piletina, tortilja, pasulj salata, crni luk, paprika, ajsberg salata":
      "Cepkana piletina, tortilja, pasulj salata, crni luk, paprika, ajsberg salata",
    "Humus, piri začin, pita hleb":
      "Humus, piri začin, pita hleb",
    "Hrskavi krompirići sa sosom od sira":
      "Hrskavi krompirići sa sosom od sira",
    "Humus, Ajvar Humus, Cvekla Humus, pita hleb":
      "Humus, Ajvar Humus, Cvekla Humus, pita hleb",
    "SUPA I SALATE": "SUPA I SALATE",
    "PILEĆA SUPA": "PILEĆA SUPA",
    "Kremasta pileća supa sa svežim povrćem servirano sa hlebom sa belim lukom.": "Kremasta pileća supa sa svežim povrćem servirano sa hlebom sa belim lukom.",
    "CAESAR SALATA": "CAESAR SALATA",
    "TABBOULEH SALATA": "TABBOULEH SALATA",
    "Bulgur, peršun,paradajz, mladi luk, sveža nana, dresing od maslina i sveže isceđenog limuna":"Bulgur, peršun,paradajz, mladi luk, sveža nana, dresing od maslina i sveže isceđenog limuna",
    "MOZZARELLA STICKS / ŠTAPIĆI": "MOZZARELLA STICKS / ŠTAPIĆI",
    "Domaći hrskavi štapići mozzarelle uvaljani u panko, servirano sa sosem.":"Domaći hrskavi štapići mozzarelle uvaljani u panko, servirano sa sosem.",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dressing":
      "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dressing",
    "GRILL MASTER'S SALATA (V)": "GRILL MASTER'S SALATA (V)",
    "Grilovani pilećin file, mix zelene i ajsberg salate, krastavac, paradajz, crni luk, paprika, marinirana cvekla, grilovani slatki kukuruz, sjenički sir, krutoni, fresh lemon dressing":
      "Grilovani pilećin file, mix zelene i ajsberg salate, krastavac, paradajz, crni luk, paprika, marinirana cvekla, grilovani slatki kukuruz, sjenički sir, krutoni, fresh lemon dressing",
    "ČETVRTINA PILETA": "ČETVRTINA PILETA",
    "GALLO'S SPECIJAL": "GALLO'S SPECIJAL",
    "Grilovana četvrtina pileta na otvorenom plamenu, prilog po izboru.": "Grilovana četvrtina pileta na otvorenom plamenu, prilog po izboru.",
    "POLA PILETA": "POLA PILETA",
    "(2x350g sa koskom)": "(2x350g sa koskom)",
    "GRILOVANI PILEĆI FILE SA POMFRITOM": "GRILOVANI PILEĆI FILE SA POMFRITOM",
    "Marinirani pileći file grilovan na otvorenom plamenu & servirano sa jednim od vaših omiljenih priloga.": "Marinirani pileći file grilovan na otvorenom plamenu & servirano sa jednim od vaših omiljenih priloga.",
    "DURBAN PILETINA": "DURBAN PILETINA",
    "Marinirani pileći batak (bez kostiju) serviran sa jednim od vaših omiljenih priloga":
      "Marinirani pileći batak (bez kostiju) serviran sa jednim od vaših omiljenih priloga",
    "Grilovani komadi pilećeg bataka (bez kostiju), grilovano povrće, servirano sa jednim od vaših omiljenih priloga":
      "Grilovani komadi pilećeg bataka (bez kostiju), grilovano povrće, servirano sa jednim od vaših omiljenih priloga",
    "DUPLI PILEĆI FILE": "DUPLI PILEĆI FILE",
    "Dva grilovana pileća filea, majonez, ajsberg salata, paradajz, čedar sir":
      "Dva grilovana pileća filea, majonez, ajsberg salata, paradajz, čedar sir",
    "WRAP SA DRPANIM PILEĆIM MESOM": "WRAP SA DRPANIM PILEĆIM MESOM",
    "Tortilja, drpana piletina, paprika, luk, šišebo sos, čedar sir, ajsberg salata":
      "Tortilja, drpana piletina, paprika, luk, šišebo sos, čedar sir, ajsberg salata",
    "Juneći burger, Prego sos, majonez, senf, ajsberg salata, kiseli krastavac, čedar sir":
      "Juneći burger, Prego sos, majonez, senf, ajsberg salata, kiseli krastavac, čedar sir",
    "GRILOVANI SIR  (V)   (BURGER/WRAP)": "GRILOVANI SIR  (V)   (BURGER/WRAP)",
    "Grilovani sir, paradajz, humus, rukola":
      "Grilovani sir, paradajz, humus, rukola",
    "ČINIJE PIRINČA": "RICE BOWLS",
    "OBROK ZA DVOJE": "OBROK ZA DVOJE",
    "PILETINA BOWL": "PILETINA BOWL",
    "Grilovani pileći file, pirinač":
      "Grilovani pileći file, pirinač",
    "BOWL SA GRILOVANOM DŽIGERICOM": "BOWL SA GRILOVANOM DŽIGERICOM",
    "Grilovana pileća džigerica, pirinač, sishebo sos":
      "Grilovana pileća džigerica, pirinač, sishebo sos",
    "PILETINA & POVRĆE":
      "PILETINA & POVRĆE",
    "Grilovani pileći file, grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilovani pileći file, grilovano povrće i pečurke, pirinač, sishebo sauce",
    "Grilovani pileći file, spanać, chili beans, pirinač":
      "Grilovani pileći file, spanać, chili beans, pirinač",
    "Grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilovano povrće i pečurke, pirinač, sishebo sauce",
    "ESPETADOS": "ESPETADOS",
    "Dva ražnjića sa komadima grilovanih pilećih bataka, grilovano povrće, servirano sa dva priloga po vašem izboru":
      "Dva ražnjića sa komadima grilovanih pilećih bataka, grilovano povrće, servirano sa dva priloga po vašem izboru",
    "1 celo pile sa 4 priloga": "1 celo pile sa 4 priloga",
    "2 cela pileta sa 6 priloga": "2 cela pileta sa 6 priloga",
    "2 predjela, 1 celo pile, 1 espetada, 4 priloga":
      "2 predjela, 1 celo pile, 1 espetada, 4 priloga",
    PRILOZI: "PRILOZI",
    "PIRINAČ": "PIRINAČ",
    POMFRIT: "POMFRIT",
    "PIRI POMFRIT": "PIRI POMFRIT",
    "SVEŽA BAŠTENSKA SALATA": "SVEŽA BAŠTENSKA SALATA",
    "BATAT POMFRIT": "BATAT POMFRIT",
    "PIRE POMFRIT": "PIRE POMFRIT",
    "GRILOVANO POVRĆE": "GRILOVANO POVRĆE",
    SPANAĆ: "SPANAĆ",
    "BROKOLI NA PARI": "BROKOLI NA PARI",
    "HLEB SA BELIM LUKOM": "HLEB SA BELIM LUKOM",
    "PASULJ SALATA": "PASULJ SALATA",
    "HRSKAVI PILEĆI WRAP": "HRSKAVI PILEĆI WRAP",
    "Hrskavi pileći file uvaljan u panko, čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom": "Hrskavi pileći file uvaljan u panko, čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom",
    "CRISPY CORNER / HRSKAVI": "CRISPY CORNER / HRSKAVI",
    "HRSKAVE PILEĆE TRAKICE": "HRSKAVE PILEĆE TRAKICE",
    "Hrskave pileće trakice servirane sa umakom i prilogom po izboru": "Hrskave pileće trakice servirane sa umakom i prilogom po izboru",
    "DOUBLE-DREDGED SHRIMP": "DOUBLE-DREDGED SHRIMP",
    "PILEĆA KRILCA - 1KG": "PILEĆA KRILCA - 1KG",
    "Hrskavi škampi, servirani sa Gallo’s umak/sos.": "Hrskavi škampi, servirani sa Gallo’s umak/sos.",
    KRILACA: "KRILACA",
    blog: "Aktuelnosti",
    blogTitle: "Aktuelnosti",
    blogSubtitle: "Budite u toku sa našim najnovijim aktuelnostima",
    back: "Nazad",
    "Nutella brownie, sladoled od vanile": "Nutella brownie, sladoled od vanile",
    "Boraniја, bob, pečeni pasulj, paprike, crni luk, naš domaći piri-piri sos sa slatko-ljutkastim ukusom": "Boraniја, bob, pečeni pasulj, paprike, crni luk, naš domaći piri-piri sos sa slatko-ljutkastim ukusom",
    "GALLO’S SIGNATURE": "GALLO’S SIGNATURE",
    "Grilovana piletina na otvorenom plamenu, servirano sa totiljom od belog luka I svežom salsom.": "Grilovana piletina na otvorenom plamenu, servirano sa totiljom od belog luka I svežom salsom.",
    "Boranija, pasulj, pečeni pasulj, paprika, crni luk domaći piri-piri slako & ljuti dressing": "Boranija, pasulj, pečeni pasulj, paprika, crni luk domaći piri-piri slako & ljuti dressing",
    "PIRE KROMPIR": "PIRE KROMPIR",
    "GRAŠAK": "GRAŠAK",
    
  },
  en: {
    KRILACA: "WINGS",
    "PASULJ SALATA": "CHILI BEAN SALAD",
    "Nutella brownie, sladoled od vanile": "Nutella brownie, vanilla ice cream",
    "Boraniја, bob, pečeni pasulj, paprike, crni luk, naš domaći piri-piri sos sa slatko-ljutkastim ukusom": "Green beans, broad beans, baked beans, peppers, onions, our homemade piri-piri sweet & chilli dressing",
    "HLEB SA BELIM LUKOM": "HLEB SA BELIM LUKOM",
    "BROKOLI NA PARI": "STEAMED BROCCOLI",
    SPANAĆ: "SPINACH",
    "GRILOVANO POVRĆE": "GRILLED VEGETABLES",
    "PIRE POMFRIT": "PIRI FRIES",
    "BATAT POMFRIT": "SWEET POTATO FRIES",
    "SVEŽA BAŠTENSKA SALATA": "FRESH GARDEN SALAD",
    "PIRI POMFRIT": "PIRI FRIES",
    POMFRIT: "FRIES",
    "PIRINAČ": "RICE",
    PRILOZI: "SIDES",
    "2 predjela, 1 celo pile, 1 espetada, 4 priloga":
      "2 starters, 1 whole chicken, 1 espetada, 4 sides",
    "Grilovana pileća krilca na otvorenom plamenu, servirano sa pomfritom, izbor sosa/Choice of spice level":
      "Grilled chicken wings on an open flame serve with fries Choice of spice level",
    "2 cela pileta sa 6 priloga": "2 whole chickens with 6 sides",
    "1 celo pile sa 4 priloga": "1 whole chicken with 4 sides",
    "Dva ražnjića sa komadima grilovanih pilećih bataka, grilovano povrće, servirano sa dva priloga po vašem izboru":
      "Two skewers of grilled cubes of boneless chicken drumbstick, grilled vegetables, served with two of your favourites sides",
    "PILEĆA ESPETADA": "CHICKEN ESPETADA",
    "ESPETADOS": "ESPETADOS",
    "Grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilled vegetables and mushrooms, rice, sishebo sauce",
    "Grilovani pileći file, spanać, chili beans, pirinač":
      "Grilled chicken breast, spinach, chili beans, rice",
    "Grilovani pileći file, grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilled chicken breast, grilled vegetables and mushrooms, rice, sishebo sauce",
    "PILETINA & POVRĆE": "CHICKEN AND VEGETABLES",
    "Grilovana pileća džigerica, pirinač, sishebo sos":
      "Grilled chicken liver, rice, sishebo sauce",
    "PILEĆA DŽIGERICA BOWL": "CHICKEN LIVER BOWL",
    "Grilovani pileći file, pirinač":
      "Grilled chicken breast, rice",
    "PILETINA BOWL": "GRILLED CHICKEN BOWL",
    "ČINIJE PIRINČA": "RICE BOWLS",
    "Grilovani sir, paradajz, humus, rukola":
      "Grilled cheese, fresh tomato, hummus, Iceberg",
    "GRILOVANI SIR  (V)   (BURGER/WRAP)": "GRILLED CHEESE  (V)   (BURGER/WRAP)",
    DEZERTI: "DESSERTS",
    "Juneći burger, Prego sos, majonez, senf, ajsberg salata, kiseli krastavac, čedar sir":
      "Beef mince, Prego sauce, mayonnaise,Iceberg, pickles and cheese",
    "Tortilja, drpana piletina, paprika, luk, šišebo sos, čedar sir, ajsberg salata":
      "Grilled chicken, onions, peppers, tomato, iceberg, mayo and cheese",
    "WRAP SA DRPANIM PILEĆIM MESOM": "PULLED CHICKEN WRAP",
    "Dva grilovana pileća filea, majonez, ajsberg salata, paradajz, čedar sir":
      "Double chicken breast, mayonnaise, Iceberg, tomato and double cheese",
    "DUPLI PILEĆI FILE": "DOUBLE-UP BURGER",
    "BURGERI I WRAPOVI": "BURGERS & WRAPS",
    "Grilovani komadi pilećeg bataka (bez kostiju), grilovano povrće, servirano sa jednim od vaših omiljenih priloga":
      "Grilled pieces of boneless chicken drumbstick, grilled vegetables, served with one of your favourites sides",
    "Marinirani pileći batak (bez kostiju) serviran sa jednim od vaših omiljenih priloga":
      "Marinated grilled boneless chicken drumbstick served with one of your favourites sides",
    "DURBAN PILETINA": "DURBAN CHICKEN",
    "Marinirani pileći file grilovan na otvorenom plamenu & servirano sa jednim od vaših omiljenih priloga.": "Marinated chicken fillet grilled on an open flame & served with one of your favorite sides.",
    "BATAK OBROK": "QUARTER LEG MEAL",
    "Grilovani pileći batak sa coleslaw  salatom": "Grilled chicken drumbstick with coleslaw salad",
    "GRILOVANI PILEĆI FILE SA POMFRITOM": "GRILLED CHICKEN FILLET WITH FRENCH FRIES",
    "(2x350g sa koskom)": "(2x350g with bone)",
    "POLA PILETA": "HALF CHICKEN",
    "Grilovana četvrtina pileta na otvorenom plamenu, prilog po izboru.": "Grilled quarter chicken over an open flame, side dish of your choice.",
    "ČETVRTINA PILETA": "QUARTER CHICKEN",
    "GALLO'S SPECIJAL": "GALLO'S SPECIAL",
    "Grilovani pilećin file, mix zelene i ajsberg salate, krastavac, paradajz, crni luk, paprika, marinirana cvekla, grilovani slatki kukuruz, sjenički sir, krutoni, fresh lemon dressing":
      "Grilled chicken breast, mix lolo and iceberg lettuce, cucumber, tomato, onion, peppers, marinated beetroot, sweet grilled corn, cottage cheese, croutons, fresh lemon dressing",
    "GRILL MASTER'S SALATA (V)": "GRILL MASTER'S SALAD (V)",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dressing":
      "Grilled chicken breast, iceberg lettuce, croutons, parmesan, homemade caesar dressing",
    "CAESAR SALATA": "CAESAR SALAD",
    "TABBOULEH SALATA": "TABBOULEH SALAD",
    "Bulgur, peršun,paradajz, mladi luk, sveža nana, dresing od maslina i sveže isceđenog limuna":"Bulgur, parsley,tomato, spring onion, fresh mint, olive and fresh lemon juice dressing",
    "SMASH BEEF BURGER": "SMASH BEEF BURGER",
    "Mlevena junetina, čedar sir, karamelizovani luk, kiseli krastavci, domaći burger sos & servirano sa pomfritom": "Ground beef, cheddar cheese, caramelized onion, pickles, homemade burger sauce & served with fries",
    "CAESAR WRAP": "CAESAR WRAP",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dresing & servirano sa pomfritom": "Grilles chicken breast, iceberg lettuce, croutons, parmesan, homemade caesar dressing",
    "PODELI OBROK": "SHARE A MEAL",
    "CELO PILE": "WHOLE CHICKEN",
    "HRSKAVI BURGER": "CRISPY BURGER",
    "Hrskavi pileći file uvaljan u panko čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom. <b>Regular / Nashville ljuti</b>": "Crispy fried chicken breast in panko, cheddar cheese, iceberg lettuce, homemade burger sauce & served with fries. Regular / Nashville Hot",
    "PILEĆI BOX 3": "CHICKEN BOX 3",
    "Tri komada piletine grilovane piletine na otvorenom plamenu, servirano sa pomfritom": "Three pieces of flame grilled chicken with fries",
    "PILEĆI BOX 5": "CHICKEN BOX 5",
    "Pet komada piletine grilovane na otvorenom plamenu, servirano sa pomfritom": "Five pieces of flame grilled chicken with fries",
    "Grilovana piletina na otvorenom plamenu, servirana uz pirinač, tortilju sa belim lukom i svežom salsom.": "Flame-grilled chicken, served with rice, a garlic tortilla, and fresh salsa.",
    "GRILOVANI PILEĆI FILE SA POMFRITOM": "GRILLED CHICKEN FILLET WITH FRENCH FRIES",
    "Grilovani pileći file": "Grilled chicken breast",
    "Četiri parčeta piletine grilovane na otvorenom plamenu, dve porcije pomfrita, ciabatta hleb, dva pića (po izboru)": "Four pieces of chicken grilled over an open flame, two portion of fries, ciabatta bread, two drinks (of your choice)",
    "Celo pile grilovano na otvorenom plamenu u prethodno odležaloj našoj specijalnoj marinadi. Servirano sa: dva priloga po vašem izboru.": "Whole chicken flame-grilled over an open fire, marinated in our special house marinade beforehand. Served with: two side dishes of your choice.",
    "Osam parčeta piletine grilovane na otvorenom plamenu, četiri porcije pomfrita, ciabatta hleb, četiri pića (po tvom izboru)": "Eight pieces of chicken grilled over an open flame, four portions of fries, ciabatta bread, four drinks (of your choice)",
    "MOZZARELLA STICKS / ŠTAPIĆI": "MOZZARELLA STICKS",
    "Domaći hrskavi štapići mozzarelle uvaljani u panko, servirano sa sosem.":"Homemade crispy mozzarella sticks coated in panko breadcrumbs, served with sauce.",
    "Kremasta pileća supa sa svežim povrćem servirano sa hlebom sa belim lukom.": "Creamy chicken soup with fresh vegetables served with garlic bread.",
    "PILEĆA SUPA": "CHICKEN SOUP",
    "SUPA I SALATE": "SOUP AND SALADS",
    "Humus, Ajvar Humus, Cvekla Humus, pita hleb":
      "Hummus, Ajvar Hummus, Beets Hummus and Pita bread",
    "GRILOVANI PILEĆI WRAP": "GRILLED CHICKEN WRAP",
    "Kokice/kockice od pohovanog pilećeg filea, pomfrit, topljeni sos od čedar sira":
      "Breaded chicken breast popcorn, fries and melted cheddar cheese sauce",
    "Mlevena piletina, homemade burger sos, sir, ajsberg": "Ground chicken, homemade burger sauce, cheese, iceberg lettuce",
    "Hrskavi krompirići sa sosom od sira": "Crispy potato fries, cheese sauce",
    "Humus, piri začin, pita hleb": "Hummus, piri seasoning, pita bread",
    "Cepkana piletina, tortilja, pasulj salata, crni luk, paprika, ajsberg salata":
      "Pulled chicken, tortilla, bean salad, onion, pepper, iceberg lettuce",
    "CEPKANI PILEĆI TAKOSI": "PULLED CHICKEN TACOS",
    "Hleb sa belim lukom sa kockicama grilovane piletine, majonezom i mocarela sirom":
      "Garlic bread topped with chicken, mayonnaise, cheese and herbs",
    "Grilovani pileći file na štapiću sa piri-piri sosem od kikirikija":
      "Grilled chicken breast skewers with piri-piri flavoured peanut sauce",
    "PILEĆI SATAY": "CHICKEN SATAY",
    "Grilovani šampinjoni u šišebo sosu i hlebom sa belim lukom i začinima":
      "Freshly grilled mushrooms, shishebo sauce, garlic bread",
    "PIRI PEČURKE (V)": "PIRISHROOMS (V) ",
    "Grilovana pileća džigerica, sishebo sos, hleb sa belim lukom":
      "Grilled chicken liver, sishebo sauce, garlic bread",
    "PILEĆA DŽIGERICA": "CHICKEN LIVER",
    PREDJELA: "STARTERS",
    "GRILOVANA PILEĆA KRILCA 500G": "GRILLED CHICKEN WINGS 500G",
    "Hrskavi krompirići sa piri-piri začinima": "Fried potato with piri-piri seasoning spices",
    "Pileća krilca grilovana na otvorenom plamenu": "Grilled chicken wings on an open flame",
    "CEPKANA PILETINA WRAP": "PULLED CHICKEN WRAP",
    "Cepkana piletina grilovana na otvorenom plamenu, crni luk, paprika, ajsberg salata, majonez, čedar, sishebo sos & servirano sa pomfritom": "Flame grilled pulled chicken, onion, pepper, iceberg lettuce, mayonnaise, cheddar cheese, sishebo sauce & served with fries",
    "Gallos obećava nezaboravne trenutke stvorene uz najukusnije pileće obroke sa roštilja na svetu.":
      "Gallos promises unforgettable moments created with the most delicious grilled chicken meals in the world.",
    "Pileće meso je marinirano u najsvežijim sastojcima najmanje 48 sati, u raznim ukusima kao što su Limun i Bilje, Blago ljuto, Ljuto i Beli luk":
      "Chicken meat is marinated in the freshest ingredients for at least 48 hours, in various flavors such as Lemon and Herb, Mild, Hot, and Garlic.",
    "Vidite naš meni": "View our menu",
    "Flame grilled chicken": "CLASSIC GRILLED",
    "FLAME GRILLED CHICKEN":"CLASSIC GRILLED",
    "CLASSIC GRILLED":"CLASSIC GRILLED",
    "CLASSIC GRILLED": "CLASSIC GRILLED",
    "GALLOS PILEĆI BURGER": "GALLOS CHICKEN BURGER",
    "Grilovani pileći file, majonez, čedar sir, paradajz & servirano sa pomfritom": "Grilled chicken breast, mayonnaise, cheddar cheese, tomatoes & served with fies",
    "PIRI PILEĆI BURGER": "PIRI CHICKEN BURGER",
    "Grilovane trake od pilećeg filea, majonez, ajsberg salata, paradajz, čedar sir & servirano sa pomfritom.": "Grilled chicken fillet strips, mayonnaise, iceberg lettuce, tomato, cheddar cheese & served with French fries.",    
    "Supe i salate": "Soups and Salads",
    "Činije pirinča": "Rice Bowls",
    Promocija: "Promotions",
    Prilozi: "Side Dishes",
    "POMFRIT": "FRENCH FRIES",
    "Ciabatta hleb, puter od belog luka": "Ciabatta bread, garlic butter",
    Jela: "Dishes",
    "Naš meni": "Our Menu",
    "Mekani kolač od urmi, sladoled od vanile, karamel sos": "Date based toffee pudding, vanilla ice cream, caramel sauce",
    "Razgovarajte sa nama": "Talk to Us",
    Meni: "Menu",
    "BASMATI PIRINAČ": "Basmati rice",
    "DEČIJI MENI": "KIDS MENU",
    "Naša istorija": "Our History",
    "PILEĆI NUGGETS": "CHICKEN NUGGETS",
    Kontakt: "Contact",
    Sosevi: "Sauces",
    "Šargarepa, kupus, majonez": "Carrots, cabbage, mayonnaise",
    "Naša priča": "Our Story",
    "Naša priča": "Our story",
    "Gallos halal piri piri piletina pečena na plamenu predstavlja pravo uživanje na tanjiru. Nudi savršen nivo ljutine u kombinaciji sa bogatim, neodoljivim slojevima ukusa. Naša kućna marinada napravljena je od 100% prirodnih sastojaka i pažljivo odabranih začina i biljaka, omogućavajući piletini da upije bogat ukus tokom najmanje 24 sata. Sveže pečena na vatri po porudžbini, sa prepoznatljivom sočnom koricom — to je najukusnija i najkvalitetnija portugalska piletina pečena na plamenu u okolini. Želite Gallos ukus i kod kuće? Nabavite naše ekskluzivne sosove, marinade ili već marinirane pileće filete (flatties) u varijantama: limun i začinsko bilje, blago i ljuto.":
      "Gallos halal flame-grilled piri piri chicken is pure comfort on a plate. It delivers that perfect level of heat paired with deep, irresistible layers of flavor. Our house marinade is blended from 100% natural ingredients and the finest hand-selected herbs and spices, giving the chicken a rich, slow infusion for at least 24 hours. Fire-grilled fresh to order for that signature juicy char — it's the most delicious and wholesome Portgues flame-grilled chicken in the area. Want the Gallos taste at home? Pick up our exclusive sauces, marinades, or pre-marinated chicken flatties in, lemon & herb, mild and hot.",
    "27 godina iskustva": "27 Years of Experience",
    "Naša hrana je srce svega što radimo.":
      "Our food is the heart of everything we do.",
    "Serviramo 100% pileće meso sa roštilja, marinirano samo najboljim sastojcima, u raznim ukusima - BBQ, Limun i Bilje, Blago ljuto, Ljuto i Extra Ljuto Piri-Piri.":
      "We serve 100% flame-grilled chicken, marinated with only the finest ingredients, in various flavors - BBQ, Lemon and Herb, Mild, Hot, and Extra Hot Piri-Piri.",

    "Nalazimo se u centru grada.": "Located in the City Center.",
    "Sveže sastojke dobavljamo sa organskih farmi.":
      "We source fresh ingredients from organic farms.",
    "Brza dostava u vlasništvu. Maksimalno 30 minuta.":
      "In-house fast delivery. Maximum 30 minutes.",
    "Profesionalni, iskusni kuvari.": "Professional, Experienced Chefs.",
    "Najviši standardi usluge.": "Highest Service Standards.",
    "100% zadovoljstvo": "100% Satisfaction",
    "ZAŠTO IZABRATI GALLO'S?": "WHY CHOOSE GALLO'S?",
    "Zato što verujemo da dobra hrana mora imati dušu. Svako jelo pripremamo s pažnjom, biramo samo proverene sastojke i trudimo se da svaki zalogaj donese isti osećaj zadovoljstva. Kod nas vas uvek čeka toplo gostoprimstvo, autentičan ukus i iskustvo kojem ćete se rado vraćati.":
      "Because we believe great food should have soul. Every dish is prepared with care, using only trusted ingredients, and crafted to deliver the same sense of satisfaction with every bite. With us, you’ll always find warm hospitality, authentic flavor, and an experience you’ll want to return to.",
    "Izvanredna usluga": "Exceptional Service",
    "Hrskavi krompirići": "Fried potato",
    "Hrana je bila izvanredna, a usluga je bila brza i vrlo profesionalna. Kvalitet obroka je bio sjajan, i zaista sam uživala u svakom zalogaju. Izvanredna usluga.":
      "The food was exceptional, and the service was fast and very professional. The meal quality was superb, and I truly enjoyed every bite. Exceptional service.",
    "Iskustvo u ovom restoranu bilo je fantastično! Hrana je bila sveža i ukusna, a osoblje je bilo veoma ljubazno. Definitivno ću se vratiti. Izvanredna usluga":
      "The experience at this restaurant was fantastic! The food was fresh and delicious, and the staff was very friendly. I will definitely return. Exceptional service.",
    "Ovaj restoran stvarno zna kako da zadovolji svoje goste. Hrana je bila sočna i puna ukusa, a usluga je bila izuzetno profesionalna. Preporučila bih ga svima!":
      "This restaurant really knows how to please its guests. The food was juicy and full of flavor, and the service was extremely professional. I would recommend it to everyone!",
    "Nisam mogao biti srećniji što sam odlučio jesti u ovom restoranu. Kvalitet hrane je bio vrhunski, a brza dostava je dodala dodatni plus. Ovo mesto je zaista vredno posete.":
      "I couldn't be happier that I decided to dine at this restaurant. The food quality was top-notch, and the fast delivery added an extra plus. This place is truly worth a visit.",
    "Piri-Piri savršenstvo": "Piri-Piri Perfection",
    "NA DOHVAT RUKE": "AT YOUR FINGERTIPS",
    "Preuzmite Gallos's aplikaciju.": "Download the Gallos's App.",
    "UKUS KAO KOD KUĆE.": "TASTE OF HOME.",
    "Hrskavi batat krompirići": "Fried batat",
    "BATAT POMFRIT": "SWEET POTATO FRIES",
    "Imamo različite Galllo's jedinstvene soseve kako biste mogli da ih isprobate kod nas.":
      "We have various Gallo’s unique sauces so you can try them here with us.",
    "HOMEMADE NUTELLA BROWNIE": "HOMEMADE NUTELLA BROWNIE",
    "STICKY DATE PUDDING": "STICKY DATE PUDDING",
    "STUPITE U KONTAKT SA NAMA": "GET IN TOUCH WITH US",
    "Ako želite da nam ispričate svoje iskustvo u Gallo'su ili želite saznati više o nama, nalazite se na pravom mestu. Pišite nam na mejl i mi ćemo vam odgovoriti.":
      "If you want to share your Gallo's experience with us or learn more about us, you're in the right place. Send us a message, and we'll get back to you.",
    "O nama": "About Us",
    "Pošalji poruku": "Send a Message",
    "Grilovane šargarepe, paprika, beli luk, pečurke, tikvice, crni luk, origano": "Grilled carrots, bell peppers, garlic, mushrooms, zucchinni, onion, oregano",
    "Naš email:": "Our Email:",
    "Kontakt telefon:": "Contact Phone:",
    "Ajsberg salata, paprika, krastavac, paradajz, italijanski dresing": "Iceberg lettuce, peppers, cucumber, tomato, italian dressing",
    "Naša adresa": "Our Address",
    "Nivo 2, Galerija Mall (parking A), Bulevar Vudroa Vilsona 12, 11000 Beograd":
      "Level 2, Galerija Mall (parking A), Boulevard Woodrow Wilson 12, 11000 Belgrade",
    "Čika Ljubina 7":
      "Čika Ljubina 7",
    Početna: "Home",
    "SLADOLED": "ICE CREAM",
    "CHEESY POMFRIT": "CHEESY FRIES",
    "Trakice pilećeg filea & servirano sa pomfritom": "Chicken breast stripes served with fries",
    "PILEĆI NUGGETS": "CHICKEN NUGGETS",
    "Kugla sladoleda od vanile": "One scoop of vanilla ice cream",
    "PILEĆI TENDERSI": "CHICKEN TENDERS",
    "Komadići pilećeg filea & servirano sa pomfritom": "Chicken breast nuggets served with fries",
    godina: "years of",
    iskustva: "experience",
    blog: "Blog",
    blogTitle: "Blog",
    blogSubtitle: "Stay up to date with our latest news",
    back: "Back",
    "PILEĆI POPCORN": "CHICKEN POPCORN",
    "Hrskavi krompirići sa topljenim čedar sirom": "Fried potato with (melted) cheddar cheese",
    "GRILL MASTER’S SALATA": "GRILL MASTER’S SALAD",
    "Pileća krilca grilovana na plamenu": "Grilled chicken wings on an open flame",
    "PILEĆI FILE": "BONELESS CHICKEN",
    "GALLO’S SIGNATURE": "GALLO’S SIGNATURE",
    "CRISPY CORNER / HRSKAVI": "CRISPY CORNER",
    "Grilovana piletina na otvorenom plamenu, servirano sa totiljom od belog luka I svežom salsom.": "Flame-grilled chicken served with garlic tortilla and fresh salsa.",
    "HRSKAVE PILEĆE TRAKICE": "CRISPY FRIED CHICKEN STRIPS",
    "Hrskave pileće trakice servirane sa umakom i prilogom po izboru": "Crispy chicken strips served with a sauce and a side of your choice.",
    "DOUBLE-DREDGED SHRIMP": "DOUBLE-DREDGED SHRIMP",
    "Hrskavi škampi, servirani sa Gallo’s umak/sos.": "Golden, crunchy shrimp served with signature dip.",
    "HRSKAVI PILEĆI WRAP": "CRISPY CHICKEN WRAP",
    "Hrskavi pileći file uvaljan u panko, čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom": "Crispy fried chicken breast in panko, cheddar cheese, iceberg lettuce, homemade burger sauce & served with fries",
    "OBROK ZA DVOJE": "MEAL FOR TWO",
    "PILEĆA KRILCA - 1KG": "CHICKEN WINGS - 1KG",
    "HLEB SA BELIM LUKOM": "GARLIC BREAD",
    "Boranija, pasulj, pečeni pasulj, paprika, crni luk domaći piri-piri slako & ljuti dressing": "Green beans, broad beans, baked beans, peppers, onions, our homemade piri-piri sweet & chilli dressing",
    "PIRE KROMPIR": "MASHED POTATOES",
    "GRAŠAK": "PEAS",
  },
};
