export const translate = {
  sr: {
    Početna: "Početna",

    "Galitos obećava nezaboravne trenutke stvorene uz najukusnije pileće obroke sa roštilja na svetu.":
      "Galitos obećava nezaboravne trenutke stvorene uz najukusnije pileće obroke sa roštilja na svetu.",
    "Pileće meso je marinirano u najsvežijim sastojcima najmanje 48 sati, u raznim ukusima kao što su Limun i Bilje, Blago ljuto, Ljuto i Beli luk":
      "Pileće meso je marinirano u najsvežijim sastojcima najmanje 48 sati, u raznim ukusima kao što su Limun i Bilje, Blago ljuto, Ljuto i Beli luk",
    "STICKY DATE PUDDING": "STICKY DATE PUDDING",
    "Trakice pilećeg filea & servirano sa pomfritom": "Trakice pilećeg filea & servirano sa pomfritom",
    "Ajsberg salata, paprika, krastavac, čeri paradajz, italijanski dresing": "Ajsberg salata, paprika, krastavac, čeri paradajz, italijanski dresing",
    "Vidite naš meni": "Vidite naš meni",
    "Flame grilled chicken": "GALITOS CLASSIC`s",
    "Supe i salate": "Supe i salate",
    "Komadići pilećeg filea & servirano sa pomfritom": "Komadići pilećeg filea & servirano sa pomfritom",
    "SLADOLED": "SLADOLED",
    "Grilovane šargarepe, paprika, beli luk, pečurke, tikvice, crni luk, origano": "Grilovane šargarepe, paprika, beli luk, pečurke, tikvice, crni luk, origano",
    "Prženi / hrskavi krompirići": "Prženi / hrskavi krompirići",
    "Činije pirinča": "RICE BOWLS",
    "Šargarepa, kupus, majonez": "Šargarepa, kupus, majonez",
    Promocija: "Promocija",
    Prilozi: "Prilozi",
    "Prženi / hrsakvi batat (krompir)": "Prženi / hrsakvi batat (krompir)",
    Jela: "Jela",
    "Naš meni": "Naš meni",
    "CHICKEN TENDERS / PILEĆI TENDERSI": "CHICKEN TENDERS / PILEĆI TENDERSI",
    "Mekani kolač od urmi, sladoled od vanile, karamel sos": "Mekani kolač od urmi, sladoled od vanile, karamel sos",
    "Razgovarajte sa nama": "Razgovarajte sa nama",
    Meni: "Meni",
    "Naša istorija": "Naša istorija",
    "DEČIJI MENI": "DEČIJI MENI",
    "Ciabatta hleb, puter od belog luka": "Ciabatta hleb, puter od belog luka",
    Kontakt: "Kontakt",
    Sosevi: "Sosevi",
    "Naša priča": "Naša priča",
    "BASMATI PIRINAČ": "Basmati pirinač",
    "CHICKEN NUGGETS / PILEĆI NUGGETSI": "CHICKEN NUGGETS / PILEĆI NUGGETSI",
    "Naša priča počinje pre 27 godina.": "Naša priča počinje pre 27 godina.",
    DEZERTI: "DEZERTI",
    "HOMEMADE NUTELLA BROWNIE": "HOMEMADE NUTELLA BROWNIE",
    "Kugla sladoleda od vanile": "Kugla sladoleda od vanile",
    "PILEĆA ESPETADA": "PILEĆA ESPETADA",
    "Osnovan u malom gradu Nelspruitu u Južnoj Africi 1996. godine, Galito's se kontinuirano širio kako u Južnoj Africi, tako i na međunarodnim tržištima.":
      "Osnovan u malom gradu Nelspruitu u Južnoj Africi 1996. godine, Galito's se kontinuirano širio kako u Južnoj Africi, tako i na međunarodnim tržištima.",
    "27 godina iskustva": "27 godina iskustva",
    "Naša hrana je srce svega što radimo.":
      "Naša hrana je srce svega što radimo.",
    "Pečena pileća krilca na otvorenom plamenu":
      "Pečena pileća krilca na otvorenom plamenu",
    "Serviramo 100% pileće meso sa roštilja, marinirano samo najboljim sastojcima, u raznim ukusima - BBQ, Limun i Bilje, Blago ljuto, Ljuto i Extra Ljuto Piri-Piri.":
      "Serviramo 100% pileće meso sa roštilja, marinirano samo najboljim sastojcima, u raznim ukusima - BBQ, Limun i Bilje, Blago ljuto, Ljuto i Extra Ljuto Piri-Piri.",
    "Nalazimo se u centru grada.": "Nalazimo se u centru grada.",
    "Sveže sastojke dobavljamo sa organskih farmi.":
      "Sveže sastojke dobavljamo sa organskih farmi.",
    "Brza dostava u vlasništvu. Maksimalno 30 minuta.":
      "Brza dostava u vlasništvu. Maksimalno 30 minuta.",
    "Profesionalni, iskusni kuvari.": "Profesionalni, iskusni kuvari.",
    "Najviši standardi usluge.": "Najviši standardi usluge.",
    "100% zadovoljstvo": "100% zadovoljstvo",
    "ZAŠTO IZABRATI GALITO'S?": "ZAŠTO IZABRATI GALITO'S?",
    "Sa više od 27 godina iskustva u franšizingu, omogućavamo potpunu podršku franšiznim partnerima širom sveta.":
      "Sa više od 27 godina iskustva u franšizingu, omogućavamo potpunu podršku franšiznim partnerima širom sveta.",
    "Izvanredna usluga": "Izvanredna usluga",
    "Prženi / hrskavi krompirići sa piri-piri začinima": "Prženi / hrskavi krompirići sa piri-piri začinima",
    "Hrana je bila izvanredna, a usluga je bila brza i vrlo profesionalna. Kvalitet obroka je bio sjajan, i zaista sam uživala u svakom zalogaju. Izvanredna usluga.":
      "Hrana je bila izvanredna, a usluga je bila brza i vrlo profesionalna. Kvalitet obroka je bio sjajan, i zaista sam uživala u svakom zalogaju.Izvanredna usluga.",
    "Iskustvo u ovom restoranu bilo je fantastično! Hrana je bila sveža i ukusna, a osoblje je bilo veoma ljubazno. Definitivno ću se vratiti. Izvanredna usluga":
      "Iskustvo u ovom restoranu bilo je fantastično! Hrana je bila sveža i ukusna, a osoblje je bilo veoma ljubazno. Definitivno ću se vratiti. Izvanredna usluga",
    "Ovaj restoran stvarno zna kako da zadovolji svoje goste. Hrana je bila sočna i puna ukusa, a usluga je bila izuzetno profesionalna. Preporučila bih ga svima!":
      "Ovaj restoran stvarno zna kako da zadovolji svoje goste. Hrana je bila sočna i puna ukusa, a usluga je bila izuzetno profesionalna. Preporučila bih ga svima!",
    "Nisam mogao biti srećniji što sam odlučio jesti u ovom restoranu. Kvalitet hrane je bio vrhunski, a brza dostava je dodala dodatni plus. Ovo mesto je zaista vredno posete.":
      "Nisam mogao biti srećniji što sam odlučio jesti u ovom restoranu. Kvalitet hrane je bio vrhunski, a brza dostava je dodala dodatni plus. Ovo mesto je zaista vredno posete.",
    "Piri-Piri savršenstvo": "Piri-Piri savršenstvo",
    "NA DOHVAT RUKE": "NA DOHVAT RUKE",
    "Preuzmite Galito's aplikaciju.": "Preuzmite Galito's aplikaciju.",
    "UKUS KAO KOD KUĆE.": "UKUS KAO KOD KUĆE.",
    "Prodajemo različite Galito's jedinstvene soseve kako biste mogli poneti iskustvo Galito'sa sa sobom kući.":
      "Prodajemo različite Galito's jedinstvene soseve kako biste mogli poneti iskustvo Galito'sa sa sobom kući.",
    "STUPITE U KONTAKT SA NAMA": "STUPITE U KONTAKT SA NAMA",
    "Ako želite da nam ispričate svoje iskustvo u Galito'su ili želite saznati više o nama, nalazite se na pravom mestu. Pišite nam na mejl i mi ćemo vam odgovoriti.":
      "Ako želite da nam ispričate svoje iskustvo u Galito'su ili želite saznati više o nama, nalazite se na pravom mestu. Pišite nam na mejl i mi ćemo vam odgovoriti.",
    "O nama": "O nama",
    "Pošalji poruku": "Pošalji poruku",
    "Naš email:": "Naš email:",
    "FLAME GRILLED CHICKEN":"GALITOS CLASSIC`s",
    "GALITOS CLASSIC`s":"GALITOS CLASSIC`s",
    "Galitos Classic`s": "GALITOS CLASSIC`s",
    "BURGERI I WRAPOVI": "BURGERI I WRAPOVI",
    "GALITOS PILEĆI BURGER": "GALITOS PILEĆI BURGER",
    "Grilovani pileći file, majonez, čedar sir, paradajz & servirano sa pomfritom": "Grilovani pileći file, majonez, čedar sir, paradajz & servirano sa pomfritom",
    "SMASH BEEF BURGER": "SMASH BEEF BURGER",
    "Mlevena junetina, majonez, čedar sir, kiseli krastavci, domaći burger sos & servirano sa pomfritom": "Mlevena junetina, majonez, čedar sir, kiseli krastavci, domaći burger sos & servirano sa pomfritom",
    "PIRI PILEĆI BURGER": "PIRI PILEĆI BURGER",
    "Trake od pilećeg filea, majonez, ajsberg salata, paradajz, čedar sir & servirano sa pomfritom": "Trake od pilećeg filea, majonez, ajsberg salata, paradajz, čedar sir & servirano sa pomfritom",
    "Kontakt telefon:": "Kontakt telefon:",
    "BATAK OBROK": "BATAK OBROK",
    "Grilovani pileći batak sa coleslaw  salatom": "Grilovani pileći batak sa coleslaw  salatom",
    "HRSKAVI BURGER": "HRSKAVI BURGER",
    "Hrskavai pileći file uvaljan u panko, čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom": "Hrskavai pileći file uvaljan u panko, čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom",
    "PODELI OBROK": "PODELI OBROK",
    "HOT BOX 3": "HOT BOX 3",
    "Tri komada piletine grilovane na otvorenom plamenu  sa pomfritom": "Tri komada piletine grilovane na otvorenom plamenu  sa pomfritom",
    "HOT BOX 5": "HOT BOX 5",
    "Pet komada piletine grilovane na otvorenom plamenu  sa pomfritom": "Pet komada piletine grilovane na otvorenom plamenu  sa pomfritom",
    "(GALITO,S) PILEĆI FILE": "(GALITO,S) PILEĆI FILE",
    "Grilovani pileći file, !!!!!!": "Grilovani pileći file, !!!!!!",
    "CEZAR WRAP": "CEZAR WRAP",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dresing & servirano sa pomfritom": "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dresing & servirano sa pomfritom",
    "Četiri parčeta piletine grilovane na otvorenom plamenu, dve porcije pomfrita, ciabatta hleb, dva pića (po tvom izboru)": "Četiri parčeta piletine grilovane na otvorenom plamenu, dve porcije pomfrita, ciabatta hleb, dva pića (po tvom izboru)",
    "Osam parčeta piletine grilovane na otvorenom plamenu, četiri porcije pomfrita, ciabatta hleb, četiri pića (po tvom izboru)": "Osam parčeta piletine grilovane na otvorenom plamenu, četiri porcije pomfrita, ciabatta hleb, četiri pića (po tvom izboru)",
    "CEPKANA PILETINA WRAP": "CEPKANA PILETINA WRAP",
    "Cepkana piletina grilovana na otvorenom plamenu, crni luk, paprika, ajsberg salata, majonez, čedar, sishebo sos & servirano sa pomfritom": "Cepkana piletina grilovana na otvorenom plamenu, crni luk, paprika, ajsberg salata, majonez, čedar, sishebo sos & servirano sa pomfritom",
    "PILEĆI WRAP": "PILEĆI WRAP",
    "Mlevena piletina, homemade burger sos, sir, ajsberg": "Mlevena piletina, homemade burger sos, sir, ajsberg",
    "Naša adresa": "Naša adresa",
    "Nivo 2, Galerija Mall (parking A), Bulevar Vudroa Vilsona 12, 11000 Beograd":
      "Nivo 2, Galerija Mall (parking A), Bulevar Vudroa Vilsona 12, 11000 Beograd",
    godina: "godina",
    iskustva: "iskustva",
    "PIRI KRILCA": "PIRI KRILCA",
    "pileća krilca grilovana na otvorenom plamenu": "pileća krilca grilovana na otvorenom plamenu",
    PREDJELA: "PREDJELA",
    "GRILOVANA PILEĆA DŽIGERICA": "GRILOVANA PILEĆA DŽIGERICA",
    "Grilovana pileća džigerica, sishebo sos, hleb sa belim lukom":
      "Grilovana pileća džigerica, sishebo sos, hleb sa belim lukom",
    "PIRI PEČURKE (V)": "PIRI PEČURKE (V)",
    "Grilovani šampinjoni u šišebo sosu i hlebom sa belim lukom i začinima":
      "Grilovani šampinjoni u šišebo sosu i hlebom sa belim lukom i začinima",
    "PILEĆI SATAY": "PILEĆI SATAY",
    "Grilovani pileći file na štapiću sa piri-piri sosem od kikirikija":
      "Grilovani pileći file na štapiću sa piri-piri sosem od kikirikija",
      "PILEĆI POPCORN": "PILEĆI POPCORN",
    "Kokice od pohovanog pilećeg filea, pomfrit, topljeni sos od čedar sira":
      "Kokice od pohovanog pilećeg filea, pomfrit, topljeni sos od čedar sira",
    "Hleb sa belim lukom sa kockicama grilovane piletine, majonezom i mocarela sirom":
      "Hleb sa belim lukom sa kockicama grilovane piletine, majonezom i mocarela sirom",
    "PILEĆI TACOS":
      "PILEĆI TACOS",
    "Takos tortilja sa čili bin i ajsberg salatom, drpana piletina sa grilovanom paprikom i lukom":
      "Takos tortilja sa čili bin i ajsberg salatom, drpana piletina sa grilovanom paprikom i lukom",
    "Humus, piri začin, pita hleb":
      "Humus, piri začin, pita hleb",
    "Hrskavi krompirići sa sosom od sira":
      "Hrskavi krompirići sa sosom od sira",
    "Humus, Ajvar Humus, Cvekla Humus, pita hleb":
      "Humus, Ajvar Humus, Cvekla Humus, pita hleb",
    "SUPA I SALATE": "SUPA I SALATE",
    "PILEĆA SUPA": "PILEĆA SUPA",
    "Kremasta pileća supa sa svežim povrćem servirano sa hlebom sa belim lukom / garlic bread": "Kremasta pileća supa sa svežim povrćem servirano sa hlebom sa belim lukom / garlic bread",
    "CAESAR SALATA": "CAESAR SALATA",
    "TABBOULEH SALATA": "TABBOULEH SALATA",
    "Bulgur, peršun,paradajz, mladi luk, sveža nana, dresing od maslina i sveže isceđenog limuna":"Bulgur, peršun,paradajz, mladi luk, sveža nana, dresing od maslina i sveže isceđenog limuna",
    "MOZZARELA ŠTAPIĆI": "MOZZARELA ŠTAPIĆI",
    "Domaći prženi štapići mozzarelle uvaljani u panko":"Domaći prženi štapići mozzarelle uvaljani u panko",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dressing":
      "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dressing",
    "GRILL MASTER'S SALATA (V)": "GRILL MASTER'S SALATA (V)",
    "Grilovani pilećin file, mix zelene i ajsberg salate, krastavac, paradajz, crni luk, paprika, marinirana cvekla, grilovani slatki kukuruz (šećerac), sjenički sir, krutoni, fresh lemon dressing":
      "Grilovani pilećin file, mix zelene i ajsberg salate, krastavac, paradajz, crni luk, paprika, marinirana cvekla, grilovani slatki kukuruz (šećerac), sjenički sir, krutoni, fresh lemon dressing",
    "ČETVRTINA PILETA": "ČETVRTINA PILETA",
    "( 350g sa koskom) ": "( 350g sa koskom) ",
    "POLA PILETA": "POLA PILETA",
    "(2x350g sa koskom)": "(2x350g sa koskom)",
    "(GALITO,S) PILEĆI FILE": "(GALITO,S) PILEĆI FILE",
    "(2x 180g filea)": "(2x 180g filea)",
    "DURBAN PILETINA": "DURBAN PILETINA",
    "Marinirani pileći batak (bez kostiju) serviran sa jednim od vaših omiljenih priloga":
      "Marinirani pileći batak (bez kostiju) serviran sa jednim od vaših omiljenih priloga",
    "Grilovani komadi pilećeg bataka (bez kostiju), grilovano povrće, servirano sa jednim od vaših omiljenih priloga":
      "Grilovani komadi pilećeg bataka (bez kostiju), grilovano povrće, servirano sa jednim od vaših omiljenih priloga",
    "DUPLI PILEĆI FILE": "DUPLI PILEĆI FILE",
    "Dva grilovana pileća filea, majonez, ajsberg salata, paradajz, čedar sir":
      "Dva grilovana pileća filea, majonez, ajsberg salata, paradajz, čedar sir",
    "WRAP SA DRPANIM PILEĆIM MESOM": "WRAP SA DRPANIM PILEĆIM MESOM",
    "Tortilja, drpana piletina, paprika, luk, šišebo sos, čedar sir, ajsberg salata":
      "Tortilja, drpana piletina, paprika, luk, šišebo sos, čedar sir, ajsberg salata",
    "Juneći burger, Prego sos, majonez, senf, ajsberg salata, kiseli krastavac, čedar sir":
      "Juneći burger, Prego sos, majonez, senf, ajsberg salata, kiseli krastavac, čedar sir",
    "GRILOVANI SIR  (V)   (BURGER/WRAP)": "GRILOVANI SIR  (V)   (BURGER/WRAP)",
    "Grilovani sir, paradajz, humus, rukola":
      "Grilovani sir, paradajz, humus, rukola",
    "ČINIJE PIRINČA": "RICE BOWLS",
    "PILETINA BOWL": "PILETINA BOWL",
    "Grilovani pileći file, pirinač":
      "Grilovani pileći file, pirinač",
    "BOWL SA GRILOVANOM DŽIGERICOM": "BOWL SA GRILOVANOM DŽIGERICOM",
    "Grilovana pileća džigerica, pirinač, sishebo sauce":
      "Grilovana pileća džigerica, pirinač, sishebo sauce",
    "PILETINA I POVRĆE BOWL":
      "PILETINA I POVRĆE BOWL",
    "Grilovani pileći file, grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilovani pileći file, grilovano povrće i pečurke, pirinač, sishebo sauce",
    "Grilovani pileći file, spanać, chili beans, pirinač":
      "Grilovani pileći file, spanać, chili beans, pirinač",
    "Grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilovano povrće i pečurke, pirinač, sishebo sauce",
    "PILEĆA COMBOTADA": "PILEĆA COMBOTADA",
    "Dva ražnjića sa pečenim kockicama pilećih bataka bez kostiju, grilovano povrće, servirano uz dva priloga po vašem izboru":
      "Dva ražnjića sa pečenim kockicama pilećih bataka bez kostiju, grilovano povrće, servirano uz dva priloga po vašem izboru",
    "1 celo pile sa 4 priloga": "1 celo pile sa 4 priloga",
    "2 cela pileta sa 6 priloga": "2 cela pileta sa 6 priloga",
    "2 predjela, 1 celo pile, 1 espetada, 4 priloga":
      "2 predjela, 1 celo pile, 1 espetada, 4 priloga",
    PRILOZI: "PRILOZI",
    "PIRINAČ": "PIRINAČ",
    POMFRIT: "POMFRIT",
    "PIRI POMFRIT": "PIRI POMFRIT",
    "SVEŽA SALATA": "SVEŽA SALATA",
    "BATAT": "BATAT",
    "PIRE POMFRIT": "PIRE POMFRIT",
    "GRILOVANO POVRĆE": "GRILOVANO POVRĆE",
    SPANAĆ: "SPANAĆ",
    "BROKOLI NA PARI": "BROKOLI NA PARI",
    "GARLIC BREAD": "GARLIC BREAD",
    "CHILI BEAN SALATA": "CHILI BEAN SALATA",
    KRILACA: "KRILACA",
    blog: "Aktuelnosti",
    blogTitle: "Aktuelnosti",
    blogSubtitle: "Budite u toku sa našim najnovijim aktuelnostima",
    back: "Nazad",
    "Nutella brownie, sladoled od vanile": "Nutella brownie, sladoled od vanile",
    "Boraniја, bob, pečeni pasulj, paprike, crni luk, naš domaći piri-piri sos sa slatko-ljutkastim ukusom": "Boraniја, bob, pečeni pasulj, paprike, crni luk, naš domaći piri-piri sos sa slatko-ljutkastim ukusom",
  },
  en: {
    KRILACA: "WINGS",
    "CHILI BEAN SALATA": "CHILI BEAN SALAD",
    "Nutella brownie, sladoled od vanile": "Nutella brownie, vanilla ice cream",
    "Boraniја, bob, pečeni pasulj, paprike, crni luk, naš domaći piri-piri sos sa slatko-ljutkastim ukusom": "Green beans, broad beans, baked beans, peppers, onions, our homemade piri-piri sweet & chilli dressing",
    "GARLIC BREAD": "GARLIC BREAD",
    "BROKOLI NA PARI": "STEAMED BROCCOLI",
    SPANAĆ: "SPINACH",
    "GRILOVANO POVRĆE": "GRILLED VEGETABLES",
    "PIRE POMFRIT": "PIRI FRIES",
    "BATAT": "SWEET POTATO FRIES",
    "SVEŽA SALATA": "FRESH GARDEN SALAD",
    "PIRI POMFRIT": "PIRI FRIES",
    POMFRIT: "FRIES",
    "PIRINAČ": "RICE",
    PRILOZI: "SIDES",
    "2 predjela, 1 celo pile, 1 espetada, 4 priloga":
      "2 starters, 1 whole chicken, 1 espetada, 4 sides",
    "Pečena pileća krilca na otvorenom plamenu":
      "Grilled chicken wings on an open flame",
    "2 cela pileta sa 6 priloga": "2 whole chickens with 6 sides",
    "1 celo pile sa 4 priloga": "1 whole chicken with 4 sides",
    "Dva ražnjića sa pečenim kockicama pilećih bataka bez kostiju, grilovano povrće, servirano uz dva priloga po vašem izboru":
      "Two skewers of grilled cubes of boneless chicken drumbstick, grilled vegetables, served with two of your favourites sides",
    "PILEĆA ESPETADA": "CHICKEN ESPETADA",
    "PILEĆA COMBOTADA": "CHICKEN COMBOTADA",
    "Grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilled vegetables and mushrooms, rice, sishebo sauce",
    "Grilovani pileći file, spanać, chili beans, pirinač":
      "Grilled chicken breast, spinach, chili beans, rice",
    "Grilovani pileći file, grilovano povrće i pečurke, pirinač, sishebo sauce":
      "Grilled chicken breast, grilled vegetables and mushrooms, rice, sishebo sauce",
    "PILETINA I POVRĆE BOWL": "CHICKEN AND VEGETABLES BOWL",
    "Grilovana pileća džigerica, pirinač, sishebo sauce":
      "Grilled chicken liver, rice, sishebo sauce",
    "PILEĆA DŽIGERICA BOWL": "CHICKEN LIVER BOWL",
    "Grilovani pileći file, pirinač":
      "Grilled chicken breast, rice",
    "PILETINA BOWL": "CHICKEN BOWL",
    "ČINIJE PIRINČA": "RICE BOWLS",
    "Grilovani sir, paradajz, humus, rukola":
      "Grilled cheese, fresh tomato, hummus, Iceberg",
    "GRILOVANI SIR  (V)   (BURGER/WRAP)": "GRILLED CHEESE  (V)   (BURGER/WRAP)",
    DEZERTI: "DESSERTS",
    "Juneći burger, Prego sos, majonez, senf, ajsberg salata, kiseli krastavac, čedar sir":
      "Beef mince, Prego sauce, mayonnaise,Iceberg, pickles and cheese",
    "Tortilja, drpana piletina, paprika, luk, šišebo sos, čedar sir, ajsberg salata":
      "Grilled chicken, onions, peppers, tomato, iceberg, mayo and cheese",
    "WRAP SA DRPANIM PILEĆIM MESOM": "PULLED CHICKEN WRAP",
    "Dva grilovana pileća filea, majonez, ajsberg salata, paradajz, čedar sir":
      "Double chicken breast, mayonnaise, Iceberg, tomato and double cheese",
    "DUPLI PILEĆI FILE": "DOUBLE-UP BURGER",
    "BURGERI I WRAPOVI": "BURGERS & WRAPS",
    "Grilovani komadi pilećeg bataka (bez kostiju), grilovano povrće, servirano sa jednim od vaših omiljenih priloga":
      "Grilled pieces of boneless chicken drumbstick, grilled vegetables, served with one of your favourites sides",
    "Marinirani pileći batak (bez kostiju) serviran sa jednim od vaših omiljenih priloga":
      "Marinated grilled boneless chicken drumbstick served with one of your favourites sides",
    "DURBAN PILETINA": "DURBAN CHICKEN",
    "(2x 180g filea)": "(2x 180g fillets)",
    "BATAK OBROK": "QUARTER LEG MEAL",
    "Grilovani pileći batak sa coleslaw  salatom": "Grilled chicken drumbstick with coleslaw salad",
    "(GALITO,S) PILEĆI FILE": "(GALITO,S) CHICKEN BREAST",
    "(2x350g sa koskom)": "(2x350g with bone)",
    "POLA PILETA": "HALF CHICKEN",
    "( 350g sa koskom) ": "( 350g with bone) ",
    "ČETVRTINA PILETA": "QUARTER CHICKEN",
    "Grilovani pilećin file, mix zelene i ajsberg salate, krastavac, paradajz, crni luk, paprika, marinirana cvekla, grilovani slatki kukuruz (šećerac), sjenički sir, krutoni, fresh lemon dressing":
      "Grilled chicken breast, mix lolo and iceberg lettuce, cucumber, tomato, onion, peppers, marinated beetroot, sweet grilled corn, cottage cheese, croutons, fresh lemon dressing",
    "GRILL MASTER'S SALATA (V)": "GRILL MASTER'S SALAD (V)",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dressing":
      "Grilled chicken breast, iceberg lettuce, croutons, parmesan, homemade caesar dressing",
    "CAESAR SALATA": "CAESAR SALAD",
    "TABBOULEH SALATA": "TABBOULEH SALAD",
    "Bulgur, peršun,paradajz, mladi luk, sveža nana, dresing od maslina i sveže isceđenog limuna":"Bulgur, parsley,tomato, spring onion, fresh mint, olive and fresh lemon juice dressing",
    "SMASH BEEF BURGER": "SMASH BEEF BURGER",
    "Mlevena junetina, majonez, čedar sir, kiseli krastavci, domaći burger sos & servirano sa pomfritom": "Ground beef, mayonnaise, cheddar cheese, pickles, homemade burger sauce & served with fries",
    "CEZAR WRAP": "CAESAR WRAP",
    "Grilovani pileći file, ajsberg salata, krutoni, parmezan, domaći caesar dresing & servirano sa pomfritom": "Grilles chicken breast, iceberg lettuce, croutons, parmesan, homemade caesar dressing",
    "PODELI OBROK": "SHARE A MEAL",
    "HRSKAVI BURGER": "CRISPY BURGER",
    "Hrskavai pileći file uvaljan u panko, čedar sir, ajsberg salata, domaći burger sos & servirano sa pomfritom": "Crispy fried chicken breast in panko, cheddar cheese, iceberg lettuce, homemade burger sauce & served with fries",
    "HOT BOX 3": "HOT BOX 3",
    "Tri komada piletine grilovane na otvorenom plamenu  sa pomfritom": "Three pieces of flame grilled chicken with fries",
    "HOT BOX 5": "HOT BOX 5",
    "Pet komada piletine grilovane na otvorenom plamenu  sa pomfritom": "Five pieces of flame grilled chicken with fries",
    "(GALITO,S) PILEĆI FILE": "(GALITO,S) CHICKEN FILLET",
    "Grilovani pileći file, !!!!!!": "Grilled chicken breast, !!!!!!",
    "Četiri parčeta piletine grilovane na otvorenom plamenu, dve porcije pomfrita, ciabatta hleb, dva pića (po tvom izboru)": "Four pieces of chicken grilled over an open flame, two portion of fries, ciabatta bread, two drinks (of your choice)",
    "Osam parčeta piletine grilovane na otvorenom plamenu, četiri porcije pomfrita, ciabatta hleb, četiri pića (po tvom izboru)": "Eight pieces of chicken grilled over an open flame, four portions of fries, ciabatta bread, four drinks (of your choice)",
    "MOZZARELA ŠTAPIĆI": "MOZZARELA STICKS",
    "Domaći prženi štapići mozzarelle uvaljani u panko":"homemade fried mozzarella sticks coated in panko (with sauce)",
    "Kremasta pileća supa sa svežim povrćem servirano sa hlebom sa belim lukom / garlic bread": "Creamy chicken soup with fresh vegetables served with garlic bread ",
    "PILEĆA SUPA": "CHICKEN SOUP",
    "SUPA I SALATE": "SOUP AND SALADS",
    "Humus, Ajvar Humus, Cvekla Humus, pita hleb":
      "Hummus, Ajvar Hummus, Beets Hummus and Pita bread",
    "PILEĆI WRAP": "CHICKEN WRAP",
    "Kokice od pohovanog pilećeg filea, pomfrit, topljeni sos od čedar sira":
      "Breaded chicken breast popcorn, fries and melted cheddar cheese sauce",
    "Mlevena piletina, homemade burger sos, sir, ajsberg": "Ground chicken, homemade burger sauce, cheese, iceberg lettuce",
    "Hrskavi krompirići sa sosom od sira": "Crispy potato fries, cheese sauce",
    "Humus, piri začin, pita hleb": "Hummus, piri seasoning, pita bread",
    "Takos tortilja sa čili bin i ajsberg salatom, drpana piletina sa grilovanom paprikom i lukom":
      "Tortilla bread, bean salad, onions, peppers, lettuce, pulled chicken",
    "PILEĆI TACOS": "CHICKEN TACOS",
    "Hleb sa belim lukom sa kockicama grilovane piletine, majonezom i mocarela sirom":
      "Garlic bread topped with chicken, mayonnaise, cheese and herbs",
    "Grilovani pileći file na štapiću sa piri-piri sosem od kikirikija":
      "Grilled chicken breast skewers with piri-piri flavoured peanut sauce",
    "PILEĆI SATAY": "CHICKEN SATAY",
    "Grilovani šampinjoni u šišebo sosu i hlebom sa belim lukom i začinima":
      "Freshly grilled mushrooms, shishebo sauce, garlic bread",
    "PIRI PEČURKE (V)": "PIRISHROOMS (V) ",
    "Grilovana pileća džigerica, sishebo sos, hleb sa belim lukom":
      "Grilled chicken liver, sishebo sauce, garlic bread",
    "GRILOVANA PILEĆA DŽIGERICA": "GRILLED CHICKEN LIVERS",
    PREDJELA: "STARTERS",
    "PIRI KRILCA": "PIRI WINGS",
    "Prženi / hrskavi krompirići sa piri-piri začinima": "Fried potato with piri-piri seasoning spices",
    "pileća krilca grilovana na otvorenom plamenu": "Grilled chicken wings on an open flame",
    "CEPKANA PILETINA WRAP": "PULLED CHICKEN WRAP",
    "Cepkana piletina grilovana na otvorenom plamenu, crni luk, paprika, ajsberg salata, majonez, čedar, sishebo sos & servirano sa pomfritom": "Flame grilled pulled chicken, onion, pepper, iceberg lettuce, mayonnaise, cheddar cheese, sishebo sauce & served with fries",
    "Galitos obećava nezaboravne trenutke stvorene uz najukusnije pileće obroke sa roštilja na svetu.":
      "Galitos promises unforgettable moments created with the most delicious grilled chicken meals in the world.",
    "Pileće meso je marinirano u najsvežijim sastojcima najmanje 48 sati, u raznim ukusima kao što su Limun i Bilje, Blago ljuto, Ljuto i Beli luk":
      "Chicken meat is marinated in the freshest ingredients for at least 48 hours, in various flavors such as Lemon and Herb, Mild, Hot, and Garlic.",
    "Vidite naš meni": "View our menu",
    "Flame grilled chicken": "GALITOS CLASSIC`s",
    "FLAME GRILLED CHICKEN":"GALITOS CLASSIC`s",
    "GALITOS CLASSIC`s":"GALITOS CLASSIC`s",
    "Galitos Classic`s": "GALITOS CLASSIC`s",
    "GALITOS PILEĆI BURGER": "GALITOS CHICKEN BURGER",
    "Grilovani pileći file, majonez, čedar sir, paradajz & servirano sa pomfritom": "Grilled chicken breast, mayonnaise, cheddar cheese, tomatoes & served with fies",
    "PIRI PILEĆI BURGER": "PIRI CHICKEN BURGER",
    "Trake od pilećeg filea, majonez, ajsberg salata, paradajz, čedar sir & servirano sa pomfritom": "Chicken breast strips, mayonnaise, iceberg lettuce, tomato, cheddar cheese & served with fries",    
    "Supe i salate": "Soups and Salads",
    "Činije pirinča": "Rice Bowls",
    Promocija: "Promotions",
    Prilozi: "Side Dishes",
    "POMFRIT": "FRENCH FRIES",
    "Ciabatta hleb, puter od belog luka": "Ciabatta bread, garlic butter",
    Jela: "Dishes",
    "Naš meni": "Our Menu",
    "Mekani kolač od urmi, sladoled od vanile, karamel sos": "Date based toffee pudding, vanilla ice cream, caramel sauce",
    "Razgovarajte sa nama": "Talk to Us",
    Meni: "Menu",
    "BASMATI PIRINAČ": "Basmati rice",
    "DEČIJI MENI": "KIDS MENU",
    "Naša istorija": "Our History",
    "CHICKEN NUGGETS / PILEĆI NUGGETSI": "CHICKEN NUGGETS",
    Kontakt: "Contact",
    Sosevi: "Sauces",
    "Šargarepa, kupus, majonez": "Carrots, cabbage, mayonnaise",
    "Naša priča": "Our Story",
    "Naša priča počinje pre 27 godina.": "Our story begins 27 years ago.",
    "Osnovan u malom gradu Nelspruitu u Južnoj Africi 1996. godine, Galito's se kontinuirano širio kako u Južnoj Africi, tako i na međunarodnim tržištima.":
      "Founded in the small town of Nelspruit, South Africa, in 1996, Galito's has continuously expanded both in South Africa and on international markets.",
    "27 godina iskustva": "27 Years of Experience",
    "Naša hrana je srce svega što radimo.":
      "Our food is the heart of everything we do.",
    "Serviramo 100% pileće meso sa roštilja, marinirano samo najboljim sastojcima, u raznim ukusima - BBQ, Limun i Bilje, Blago ljuto, Ljuto i Extra Ljuto Piri-Piri.":
      "We serve 100% flame-grilled chicken, marinated with only the finest ingredients, in various flavors - BBQ, Lemon and Herb, Mild, Hot, and Extra Hot Piri-Piri.",

    "Nalazimo se u centru grada.": "Located in the City Center.",
    "Sveže sastojke dobavljamo sa organskih farmi.":
      "We source fresh ingredients from organic farms.",
    "Brza dostava u vlasništvu. Maksimalno 30 minuta.":
      "In-house fast delivery. Maximum 30 minutes.",
    "Profesionalni, iskusni kuvari.": "Professional, Experienced Chefs.",
    "Najviši standardi usluge.": "Highest Service Standards.",
    "100% zadovoljstvo": "100% Satisfaction",
    "ZAŠTO IZABRATI GALITO'S?": "WHY CHOOSE GALITO'S?",
    "Sa više od 27 godina iskustva u franšizingu, omogućavamo potpunu podršku franšiznim partnerima širom sveta.":
      "With over 27 years of franchising experience, we provide full support to franchise partners worldwide.",
    "Izvanredna usluga": "Exceptional Service",
    "Prženi / hrskavi krompirići": "Fried potato",
    "Hrana je bila izvanredna, a usluga je bila brza i vrlo profesionalna. Kvalitet obroka je bio sjajan, i zaista sam uživala u svakom zalogaju. Izvanredna usluga.":
      "The food was exceptional, and the service was fast and very professional. The meal quality was superb, and I truly enjoyed every bite. Exceptional service.",
    "Iskustvo u ovom restoranu bilo je fantastično! Hrana je bila sveža i ukusna, a osoblje je bilo veoma ljubazno. Definitivno ću se vratiti. Izvanredna usluga":
      "The experience at this restaurant was fantastic! The food was fresh and delicious, and the staff was very friendly. I will definitely return. Exceptional service.",
    "Ovaj restoran stvarno zna kako da zadovolji svoje goste. Hrana je bila sočna i puna ukusa, a usluga je bila izuzetno profesionalna. Preporučila bih ga svima!":
      "This restaurant really knows how to please its guests. The food was juicy and full of flavor, and the service was extremely professional. I would recommend it to everyone!",
    "Nisam mogao biti srećniji što sam odlučio jesti u ovom restoranu. Kvalitet hrane je bio vrhunski, a brza dostava je dodala dodatni plus. Ovo mesto je zaista vredno posete.":
      "I couldn't be happier that I decided to dine at this restaurant. The food quality was top-notch, and the fast delivery added an extra plus. This place is truly worth a visit.",
    "Piri-Piri savršenstvo": "Piri-Piri Perfection",
    "NA DOHVAT RUKE": "AT YOUR FINGERTIPS",
    "Preuzmite Galito's aplikaciju.": "Download the Galito's App.",
    "UKUS KAO KOD KUĆE.": "TASTE OF HOME.",
    "Prženi / hrsakvi batat (krompir)": "Fried batat",
    "BATAT": "Sweet potato fries",
    "Prodajemo različite Galito's jedinstvene soseve kako biste mogli poneti iskustvo Galito'sa sa sobom kući.":
      "We sell various unique Galito's sauces so you can take the Galito's experience home with you.",
    "HOMEMADE NUTELLA BROWNIE": "HOMEMADE NUTELLA BROWNIE",
    "STICKY DATE PUDDING": "STICKY DATE PUDDING",
    "STUPITE U KONTAKT SA NAMA": "GET IN TOUCH WITH US",
    "Ako želite da nam ispričate svoje iskustvo u Galito'su ili želite saznati više o nama, nalazite se na pravom mestu. Pišite nam na mejl i mi ćemo vam odgovoriti.":
      "If you want to share your Galito's experience with us or learn more about us, you're in the right place. Send us a message, and we'll get back to you.",
    "O nama": "About Us",
    "Pošalji poruku": "Send a Message",
    "Grilovane šargarepe, paprika, beli luk, pečurke, tikvice, crni luk, origano": "Grilled carrots, bell peppers, garlic, mushrooms, zucchinni, onion, oregano",
    "Naš email:": "Our Email:",
    "Kontakt telefon:": "Contact Phone:",
    "Ajsberg salata, paprika, krastavac, čeri paradajz, italijanski dresing": "Iceberg lettuce, peppers, cucumber, cherry tomato, italian dressing",
    "Naša adresa": "Our Address",
    "Nivo 2, Galerija Mall (parking A), Bulevar Vudroa Vilsona 12, 11000 Beograd":
      "Level 2, Galerija Mall (parking A), Boulevard Woodrow Wilson 12, 11000 Belgrade",
    Početna: "Home",
    "SLADOLED": "ICE CREAM",
    "Trakice pilećeg filea & servirano sa pomfritom": "Chicken breast stripes served with fries",
    "CHICKEN NUGGETS / PILEĆI NUGGETSI": "CHICKEN NUGGETS / PILEĆI NUGGETSI",
    "Kugla sladoleda od vanile": "One scoop of vanilla ice cream",
    "CHICKEN TENDERS / PILEĆI TENDERSI": "CHICKEN TENDERS",
    "Komadići pilećeg filea & servirano sa pomfritom": "Chicken breast nuggets served with fries",
    godina: "years of",
    iskustva: "experience",
    blog: "Blog",
    blogTitle: "Blog",
    blogSubtitle: "Stay up to date with our latest news",
    back: "Back",
  },
};
